### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by AeonLucid** [programa-stic/snapchat-decrypt#7] opened 2015-02-23 17:25 UTC
Script doesn't work for latest snapchat, 9.1.2.0.
Any information on 9.1.2.0?

**Comment by xeroxnir** [comment] 2015-02-23 19:17
Hello, the latest Snapchat appears to have stopped caching the keys in the "bananas1" file and instead just downloads the image again from the network when closing instead of using the already downloaded one. So far I haven't found a way around it.
Joaquín

**Comment by AeonLucid** [comment] 2015-02-23 19:39
Is it possible to use an old version of snapchat?

**Comment by xeroxnir** [comment] 2015-02-23 19:41
Yes, you can use any of the older versions greater than 5.0.34.X, they are still working.
Joaquín

**Comment by AeonLucid** [comment] 2015-02-23 19:46
Got any link for me where I can find the latest one working with this python script?

**Comment by xeroxnir** [comment] 2015-02-23 19:48
Here you can download different versions: http://snapchat.en.uptodown.com/android/old

**Comment by AeonLucid** [comment] 2015-02-23 20:19
The bananas file now is there however my adb pull isn't successfull.
I get:
aeonlucid@spacious:~/snapchat$ sudo adb pull /data/data/com.snapchat.android/cache/received_image_snaps/ encrypted_received_image_snaps/
pull: building file list...
0 files pulled. 0 files skipped.

However, when I check that directory with ES File Explorer (root) there is a file.
How can I solve this?

**Comment by xeroxnir** [comment] 2015-02-23 20:20
Is adb runing as root? Are you using ADBDinsecure for example?

**Comment by AeonLucid** [comment] 2015-02-23 20:21
I use to one provided with 
sudo apt-get install android-tools-adb android-tools-fastboot (Ubuntu Server 14.04.2)

Do you have a link to the adb I should use?

**Comment by xeroxnir** [comment] 2015-02-23 20:23
The problem is not in the PC but in the device, when you run adb do you get the symbol $ instead of # at the start? you should install http://forum.xda-developers.com/showthread.php?t=1687590 so adb runs as root from the start.

**Comment by AeonLucid** [comment] 2015-02-23 20:26
Thanks mate, I got it working. :)

**Comment by AeonLucid** [comment] 2015-02-23 20:34
@zerokes, can I add you somewhere. I'd like to ask some things privately.

**Comment by xeroxnir** [comment] 2015-02-23 20:40
Hi, you can reach me at jrinaudo@fundacionsadosky.org.ar.

**Closed as completed** 2017-05-28 23:14 UTC
